sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t icannomnoms/react-test -f ./complex/client/Dockerfile.dev ./client

script:
  - docker run -e CI=true icannomnoms/react-test npm test

after_success:
  - docker build -t icannomnoms/multi-client ./complex/client
  - docker build -t icannomnoms/multi-nginx ./complex/nginx
  - docker build -t icannomnoms/multi-server ./complex/server
  - docker build -t icannomnoms/multi-worker ./complex/worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push icannomnoms/multi-client
  - docker push icannomnoms/multi-nginx
  - docker push icannomnoms/multi-server
  - docker push icannomnoms/multi-worker
